baseURL = "//ruqqq.sg"
languageCode = "en-us"
title = "ruqqq's Ramblings"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/ruqqq\">Faruq Rasid</a> 2018"
Paginate = 5
enableRobotsTXT = true

[params.info]
enableSocial = true
poweredby = false
homeTitle = "ruqqq's Ramblings"

[params.social]
twitter = "ruqqq"
github = "ruqqq"
linkedin = "faruqrasid"
facebook = "mohd.faruq"
instagram = "ruqqq"

[blackfriday]
hrefTargetBlank = true
